// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const intro: string;
export const container: string;
export const title: string;
export const paragraph: string;
export const subtitle: string;
export const name: string;
export const accent: string;
export const link: string;
