// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const greetings__div: string;
export const greetingsContainer__div: string;
export const title__h1: string;
export const subtitle__p: string;
export const name__span: string;
export const accent__text: string;
export const link__a: string;
