// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const posts__ol: string;
export const postsItem__li: string;
export const postsItem__p: string;
export const postItem__h2: string;
export const postItem__header: string;
