// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const postList: string;
export const postListItem: string;
export const postListItemParagraph: string;
export const postListItemH2: string;
export const postListItemHeader: string;
